#!/usr/bin/env Rscript
# Regenerates extension/common/municipios.js from orcedata::municipios —
# the código IBGE -> "MUNICÍPIO - UF" lookup the Guia do Dia's Lab tab uses
# to name each visit's município from the first 7 digits of its Controle.
#
# Storage is compressed ~2x versus a plain {código: "NOME - UF"} object,
# because the table ships inside the extension:
#   * grouped by the 2-digit UF prefix, so " - BA" is stored once per UF
#     rather than once per município;
#   * of the 7 digits, the first 2 are the UF and the 7th is IBGE's check
#     digit, so only the middle 4 identify the município WITHIN its UF —
#     verified unique below. 3 digits is NOT enough (it collides), and the
#     middle 4 alone are NOT unique nationally (850 are reused across UFs),
#     which is exactly why the runtime table stays UF-scoped;
#   * each UF is one delimited string, parsed into a Map on first lookup,
#     instead of 5571 object literals.
suppressMessages(library(sf))
data(municipios, package = "orcedata")

d <- sf::st_drop_geometry(municipios)
d <- d[order(d$municipio_codigo), ]

codigo <- as.character(d$municipio_codigo)
uf <- substr(codigo, 1, 2)
mid <- substr(codigo, 3, 6)
nome <- toupper(d$municipio_nome)

# Invariants the runtime parser depends on — fail the build, never ship a
# silently wrong table.
stopifnot(
  all(nchar(codigo) == 7),
  !anyDuplicated(paste0(uf, mid)),          # unique within each UF
  # Pipe is the delimiter and backslash/double-quote would break the JS
  # string literal. Apostrophes are fine (47 names have one, e.g. "ALTA
  # FLORESTA D'OESTE") — entries are emitted double-quoted.
  !any(grepl('[|"\\\\]', nome)),
  !any(grepl('[|"\\\\]', d$uf_sigla))
)

ufs <- unique(uf)
packed <- tapply(paste0(mid, nome), uf, paste, collapse = "|")[ufs]
sigla <- tapply(as.character(d$uf_sigla), uf, function(x) x[1])[ufs]

entries <- sprintf('    %s: "%s|%s",', ufs, sigla, packed)

writeLines(c(
  "// Generated by scripts/gen-municipios.R from orcedata::municipios — do not",
  "// edit by hand. Maps the 7-digit IBGE município code (the first 7 digits of",
  "// a Controle) to its \"MUNICÍPIO - UF\" label.",
  "//",
  "// Packed one entry per UF to keep the shipped table small: each value is",
  "// 'SIGLA|CCCCNOME|CCCCNOME|…' where CCCC is digits 3-6 of the código. The",
  "// first 2 digits are the UF prefix and the 7th is a check digit, so those 4",
  "// identify the município within its UF (unique — asserted by the generator).",
  "// They are NOT unique nationally, so lookup is always UF-scoped. Each UF is",
  "// parsed into a Map lazily, once, on first lookup.",
  "(function () {",
  "  'use strict';",
  "",
  "  const PACKED = {",
  entries,
  "  };",
  "",
  "  // uf prefix -> Map(4-digit code -> 'NOME - UF'), built on demand.",
  "  const cache = new Map();",
  "",
  "  function ufTable(uf) {",
  "    const cached = cache.get(uf);",
  "    if (cached) return cached;",
  "    const packed = PACKED[uf];",
  "    if (!packed) return null;",
  "    const parts = packed.split('|');",
  "    const sigla = parts[0];",
  "    const table = new Map();",
  "    for (let i = 1; i < parts.length; i += 1) {",
  "      table.set(parts[i].slice(0, 4), `${parts[i].slice(4)} - ${sigla}`);",
  "    }",
  "    cache.set(uf, table);",
  "    return table;",
  "  }",
  "",
  "  // '2927408012345' -> 'SALVADOR - BA'. Returns '' for anything that isn't",
  "  // a known código: short/absent Controle, or a code not in the table.",
  "  function municipioFromControle(controle) {",
  "    const digits = String(controle ?? '').replace(/\\D/g, '');",
  "    if (digits.length < 7) return '';",
  "    const table = ufTable(digits.slice(0, 2));",
  "    return (table && table.get(digits.slice(2, 6))) || '';",
  "  }",
  "",
  "  // Augments the object sigc-common.js creates — it assigns",
  "  // window.__sigcPro wholesale, so this file MUST load after it",
  "  // (see manifest.json content_scripts order).",
  "  window.__sigcPro = window.__sigcPro || {};",
  "  window.__sigcPro.municipioFromControle = municipioFromControle;",
  "}());"
), "extension/common/municipios.js")

cat("wrote extension/common/municipios.js —", nrow(d), "municípios,",
    length(ufs), "UFs\n")
